on:
  push:
    branches:
      - main
  pull_request:

name: Run tests
jobs:
  wkt:
    name: wkt
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    container:
      image: georust/geo-ci
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, clippy, rust-src
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-features --all-targets -- -Dwarnings
      - run: cargo test --all-features
      - run: cargo test --no-default-features
