on:
  push:
    branches:
      - main
  pull_request:

name: Run tests
jobs:
  wkb:
    name: wkb
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, clippy, rust-src
      - name: Install dependencies
        shell: bash
        run: |
          rustc --version
          cargo --version
          sudo apt-get update
          sudo apt-get install -y libgeos-dev
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-features --all-targets -- -Dwarnings
      - run: cargo test --all-features
      - run: cargo test --no-default-features
      # We run this on CI as a test that recursive writing of geometry/geometry
      # collections can compile. See https://github.com/kylebarron/wkb/issues/15
      - run: cargo bench --bench parse
